version: "3"

services:
  app:
    image: jupyter/minimal-notebook
    container_name: jupyter
    restart: unless-stopped
    volumes:
      - notebook:/home/jovyan/work
    ports:
      - 80:8888
    environment:
      - JUPYTER_TOKEN=ThisIsSecret

volumes:
  notebook: