version: "3"

services:
  app:
    image: jupyter/datascience-notebook:2023-06-29
    container_name: jupyter
    restart: unless-stopped
    volumes:
      - notebook:/home/jovyan
    ports:
      - 80:8888
    environment:
      - JUPYTER_TOKEN=ThisIsSecret

volumes:
  notebook: