version: '3.1'

services:
  database:
    image: mysql:5.7
    container_name: db-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=ThisIsSecret
      - MYSQL_ROOT_PASSWORD=them45t3r
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - net
    command: '--default-authentication-plugin=mysql_native_password'

  app:
    depends_on: 
      - database
    image: wordpress:php8.2-fpm-alpine
    container_name: app-wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD=ThisIsSecret
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wpdata:/var/www/html
    networks:
      - net
  
  proxy:
    depends_on:
      - app
    build: 
      dockerfile: Dockerfile
      args:
        - WP_HOST=app
    container_name: proxy-nginx
    restart: unless-stopped
    volumes:
      - wpdata:/var/www/html
    ports:
      - 80:80
    links:
      - app
    networks:
      - net
    

networks:
  net:
    driver: bridge

volumes:
  wpdata:
  dbdata: